/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package espoch.edu.ec.practicagrupal;

/**
 *
 * @author mundo
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTurno = new javax.swing.ButtonGroup();
        btnOpcion = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        txtEscrito = new javax.swing.JTextField();
        cbxOpcions = new javax.swing.JComboBox<>();
        cbxTransporte = new javax.swing.JCheckBox();
        cbxAlmuerzo = new javax.swing.JCheckBox();
        cbxMaterial = new javax.swing.JCheckBox();
        rbtMañana = new javax.swing.JRadioButton();
        rbtTarde = new javax.swing.JRadioButton();
        lblTurnno = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaMostrarDatos = new javax.swing.JTextArea();
        lblServicios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblTitulo.setText("Registro de Participantes:");

        btnRegistrar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        lblNombre.setText("Ingrese su Nombre");

        btnMostrar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        cbxOpcions.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        cbxOpcions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Profesional", "Invitado Especial" }));
        cbxOpcions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxOpcionsActionPerformed(evt);
            }
        });

        btnOpcion.add(cbxTransporte);
        cbxTransporte.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        cbxTransporte.setText("Transporte");
        cbxTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTransporteActionPerformed(evt);
            }
        });

        btnOpcion.add(cbxAlmuerzo);
        cbxAlmuerzo.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        cbxAlmuerzo.setText("Almuerzo");

        btnOpcion.add(cbxMaterial);
        cbxMaterial.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        cbxMaterial.setText("Material de Apoyo");
        cbxMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMaterialActionPerformed(evt);
            }
        });

        btnTurno.add(rbtMañana);
        rbtMañana.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rbtMañana.setText("Mañana");

        btnTurno.add(rbtTarde);
        rbtTarde.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rbtTarde.setText("Tarde");
        rbtTarde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtTardeActionPerformed(evt);
            }
        });

        lblTurnno.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblTurnno.setText("Turno: ");

        txtaMostrarDatos.setColumns(20);
        txtaMostrarDatos.setRows(5);
        jScrollPane1.setViewportView(txtaMostrarDatos);

        lblServicios.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblServicios.setText("Servicios Requeridos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(rbtMañana)
                                .addGap(116, 116, 116)
                                .addComponent(rbtTarde))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblTitulo)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNombre)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtEscrito, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(cbxOpcions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(279, 279, 279)
                                        .addComponent(cbxMaterial))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbxAlmuerzo)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(116, 116, 116)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblServicios)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblTurnno)
                                                        .addComponent(cbxTransporte)))))
                                        .addGap(173, 173, 173)))))))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(273, 273, 273))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtEscrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxOpcions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(lblServicios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTransporte)
                    .addComponent(cbxAlmuerzo)
                    .addComponent(cbxMaterial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTurnno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtMañana)
                    .addComponent(rbtTarde))
                .addGap(28, 28, 28)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMostrar)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String [] datosUsuario=new String[6];
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String nombre = txtEscrito.getText();
        String ocupacion= (String) cbxOpcions.getSelectedItem();
        String almuerzo = cbxAlmuerzo.isSelected()?"Almuerzo ":" ";
        String transporte =cbxTransporte.isSelected()?"Transporte ":" ";
        String material = cbxMaterial.isSelected()?"Material ":" ";
        boolean mañana =rbtMañana.isSelected();
        boolean tarde = rbtTarde.isSelected();
        
        String turno="";
        if (mañana) {
            turno="Jordana de la mañana";
        } else if (tarde){
            turno="Jornada de la tarde";
        }
        
        datosUsuario[0]=nombre;
        datosUsuario[1]=ocupacion;
        datosUsuario[2]=almuerzo;
        datosUsuario[3]=transporte;
        datosUsuario[4]=material;
        datosUsuario[5]=turno;
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        String datos = "";
        
        for (int i = 0; i < 6; i++) {
            System.out.println("Los datos del participante es: "+datosUsuario[i]);
            datos=datos+","+datosUsuario[i];
        } 
            txtaMostrarDatos.setText(datos);
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void cbxOpcionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxOpcionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxOpcionsActionPerformed

    private void cbxTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTransporteActionPerformed

    private void cbxMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMaterialActionPerformed

    private void rbtTardeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtTardeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtTardeActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.ButtonGroup btnOpcion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.ButtonGroup btnTurno;
    private javax.swing.JCheckBox cbxAlmuerzo;
    private javax.swing.JCheckBox cbxMaterial;
    private javax.swing.JComboBox<String> cbxOpcions;
    private javax.swing.JCheckBox cbxTransporte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblServicios;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTurnno;
    private javax.swing.JRadioButton rbtMañana;
    private javax.swing.JRadioButton rbtTarde;
    private javax.swing.JTextField txtEscrito;
    private javax.swing.JTextArea txtaMostrarDatos;
    // End of variables declaration//GEN-END:variables
}
